sudo: required
language: node_js
addons:
  chrome: stable
services:
  - xvfb
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: wFz86YP9em1YD6903hkJESff/BJGHHtpRThkM8ixum6GN8jYfnJHYTPDHh1yxT6OgCxE6oaTCwk0CefnFlosbjpcWuLl5opRgtKhACfDc5J8JNBbOtxsQrTyx3ag97G/N3SVzazWN9cHmfG4VV3UMeL6HHv67GrhWlMTY0W4xus=
